import { StyleSheet } from "react-native";
import { BizzusColors, Fonts, MyColors } from "../../../theme/AppTheme";

const ProductListStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: BizzusColors.cream,
    },
    emptyContainer: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        padding: 30,
    },
    emptyText: {
        color: BizzusColors.mist,
        fontSize: 14,
        textAlign: 'center',
        marginTop: 20,
    },
    listContent: {
        padding: 18,
        paddingBottom: 100,
    },
    tag: {
        color: BizzusColors.gold,
        fontSize: 11,
        fontWeight: '700',
        letterSpacing: 1.5,
    },
    pageTitle: {
        fontFamily: Fonts.serif,
        fontSize: 24,
        fontWeight: '700',
        color: BizzusColors.ink,
        marginTop: 4,
    },
    pageSubtitle: {
        color: BizzusColors.mist,
        fontSize: 12,
        marginTop: 4,
        marginBottom: 14,
    },
    reportsToggle: {
        alignSelf: 'flex-start',
        borderWidth: 1.5,
        borderColor: BizzusColors.ink,
        borderRadius: 20,
        paddingHorizontal: 14,
        paddingVertical: 8,
        marginBottom: 16,
    },
    reportsToggleText: {
        fontSize: 12,
        fontWeight: '700',
        color: BizzusColors.ink,
    },
    statsGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 10,
        marginBottom: 16,
    },
    statCard: {
        flexBasis: '47%',
        flexGrow: 1,
        backgroundColor: '#fff',
        borderRadius: 12,
        padding: 14,
        borderWidth: 1,
        borderColor: BizzusColors.border,
    },
    statValue: {
        fontFamily: Fonts.serif,
        fontSize: 22,
        fontWeight: '700',
    },
    statLabel: {
        fontSize: 10,
        color: BizzusColors.mist,
        textTransform: 'uppercase',
        marginTop: 2,
        letterSpacing: 0.5,
    },
    statGold: { color: BizzusColors.gold },
    statBlue: { color: '#3498db' },
    statGreen: { color: BizzusColors.success },
    statRust: { color: BizzusColors.rust },
    search: {
        borderWidth: 1.5,
        borderColor: BizzusColors.border,
        borderRadius: 10,
        paddingHorizontal: 14,
        paddingVertical: 10,
        fontSize: 14,
        marginBottom: 10,
        backgroundColor: '#fff',
        color: BizzusColors.ink,
    },
    chip: {
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: 20,
        borderWidth: 1,
        borderColor: BizzusColors.border,
        marginRight: 8,
        backgroundColor: '#fff',
    },
    chipActive: {
        backgroundColor: BizzusColors.ink,
        borderColor: BizzusColors.ink,
    },
    chipText: {
        fontSize: 12,
        color: BizzusColors.ink,
        fontWeight: '600',
        textTransform: 'capitalize',
    },
    chipTextActive: {
        color: '#fff',
    },
    card: {
        flexDirection: 'row',
        backgroundColor: 'white',
        borderRadius: 14,
        padding: 12,
        marginBottom: 14,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: BizzusColors.border,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.06,
        shadowRadius: 6,
        elevation: 2,
    },
    cardImage: {
        width: 52,
        height: 62,
        borderRadius: 8,
        backgroundColor: BizzusColors.warm,
    },
    cardInfo: {
        flex: 1,
        marginLeft: 12,
    },
    cardName: {
        fontWeight: 'bold',
        fontSize: 15,
        color: BizzusColors.ink,
    },
    cardDescription: {
        color: BizzusColors.mist,
        fontSize: 12,
        marginTop: 2,
    },
    baseTag: {
        color: BizzusColors.gold,
        fontSize: 10,
        fontWeight: '700',
        marginTop: 2,
        textTransform: 'uppercase',
    },
    cardFooterRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginTop: 6,
    },
    cardCategory: {
        color: MyColors.secondary,
        fontSize: 11,
        fontWeight: 'bold',
        textTransform: 'capitalize',
    },
    cardPrice: {
        color: MyColors.primary,
        fontSize: 13,
        fontWeight: 'bold',
    },
    stockText: {
        fontSize: 11,
        color: BizzusColors.mist,
        fontWeight: '600',
    },
    stockLow: {
        color: BizzusColors.rust,
    },
    badge: {
        paddingHorizontal: 8,
        paddingVertical: 2,
        borderRadius: 20,
    },
    badgeOk: {
        backgroundColor: BizzusColors.successBg,
    },
    badgeBad: {
        backgroundColor: '#fdecea',
    },
    badgeText: {
        fontSize: 9,
        fontWeight: '700',
    },
    badgeTextOk: {
        color: BizzusColors.success,
    },
    badgeTextBad: {
        color: BizzusColors.rust,
    },
    cardActions: {
        flexDirection: 'column',
        gap: 12,
        marginLeft: 8,
    },
    actionIcon: {
        width: 20,
        height: 20,
    },
    fab: {
        position: 'absolute',
        right: 20,
        bottom: 20,
        width: 60,
        height: 60,
        borderRadius: 30,
        backgroundColor: BizzusColors.ink,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 4,
    },
    fabIcon: {
        width: 28,
        height: 28,
        tintColor: 'white',
    },
});

export default ProductListStyles;
